id: AE10AA016
base_file: f4C1C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:12:42.911333
  last_modified_at: 2022-05-30 22:12:42.911337
